library(ggplot2)
data <- read.csv("Ldh.csv", header = T, check.names = F)
data$phylum <- factor(data$phylum,levels = c("Proteobacteria","Planctomycetota","Desulfobacterota_B","Methylomirabilota","Chloroflexota"))
mycol <- c("#d4a6c8","#f1ce63","#fabfd2","#ff9d9a","#e15759")
p <- ggplot(data, aes(x=gene, y=num, fill=phylum)) + geom_bar(stat = "identity",position ="fill") + scale_fill_manual(values=mycol) + labs(x = "Sample" , y = "Relative abundance(%)") + theme(axis.title=element_text(size=15),axis.text.x = element_text(angle=45, hjust = 1, vjust = 1 ,size = 12),axis.text.y = element_text(size = 12),axis.ticks.length=unit(0.15,"cm") ,panel.background = element_blank(),axis.line = element_line(color = "black"))
ggsave("Ldh.pdf",p,width = 8,height = 8)